FROM tensorflow/tensorflow:0.12.1

WORKDIR /root

RUN apt-get update
RUN apt-get install -y git wget ttf-freefont tmux openssh-server
RUN apt-get clean

RUN pip install prettytensor==0.7.3 progressbar python-dateutil easydict pandas torchfile pillow pyyaml ipdb numpy==1.11.3 jupyter

RUN mkdir  /root/scripts
COPY start.sh /root/scripts/

RUN echo "c.NotebookApp.token = ''" >> /root/.jupyter/jupyter_notebook_config.py && echo "c.NotebookApp.base_url = '/'" >> /root/.jupyter/jupyter_notebook_config.py


CMD /root/scripts/start.sh
